// src/components/ChannelChart.tsx
'use client';

import { Bar, BarChart, LabelList, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { money, pct } from '@/lib/data';

type Row = { channel: string; revenue: number };

// One series, so one colour for every bar; values are labelled directly at the bar ends.
export default function ChannelChart({ data }: { data: Row[] }) {
  const total = data.reduce((s, d) => s + d.revenue, 0);
  return (
    <div className="chart" role="img" aria-label={`Revenue by channel: ${data.map((d) => `${d.channel} ${money(d.revenue)}`).join(', ')}.`}>
      <ResponsiveContainer width="100%" height={data.length * 44 + 8}>
        <BarChart data={data} layout="vertical" margin={{ top: 0, right: 64, bottom: 0, left: 0 }} barCategoryGap={10}>
          <XAxis type="number" hide />
          <YAxis type="category" dataKey="channel" tickLine={false} axisLine={false} width={116} tick={{ fill: 'var(--text-2)', fontSize: 13 }} />
          <Tooltip cursor={{ fill: 'var(--hover)' }} content={({ active, payload }) => active && payload?.length ? (
            <div className="tip">
              <p className="tip-row"><b>{money(payload[0].value as number)}</b><span>{pct((payload[0].value as number) / total)} of revenue</span></p>
            </div>
          ) : null} />
          <Bar dataKey="revenue" fill="var(--series-1)" radius={[0, 4, 4, 0]} isAnimationActive={false}>
            <LabelList dataKey="revenue" position="right" formatter={(v) => `$${Math.round(Number(v) / 1000)}k`} fill="var(--text-2)" fontSize={12} />
          </Bar>
        </BarChart>
      </ResponsiveContainer>
    </div>
  );
}

// app/components/ChannelChart.vue
<script setup lang="ts">
import { money, pct } from '~/utils/data';

// One series, so one colour for every bar; values are labelled at the bar ends.
// Built from plain HTML so it scales with the card; hovering or focusing a bar shows its share.
const props = defineProps<{ data: { channel: string; revenue: number }[] }>();
const total = computed(() => props.data.reduce((s, d) => s + d.revenue, 0));
const max = computed(() => Math.max(...props.data.map((d) => d.revenue)));
const active = ref<string | null>(null);
</script>

<template>
  <ul class="bars" :aria-label="`Revenue by channel: ${data.map((d) => `${d.channel} ${money(d.revenue)}`).join(', ')}.`">
    <li
      v-for="d in data" :key="d.channel" class="bar-row" tabindex="0"
      @pointerenter="active = d.channel" @pointerleave="active = null" @focus="active = d.channel" @blur="active = null"
    >
      <span class="bar-label">{{ d.channel }}</span>
      <span class="bar-track">
        <span class="bar" :style="{ width: `${(d.revenue / max) * 100}%` }" />
        <span class="bar-value">${{ Math.round(d.revenue / 1000) }}k</span>
      </span>
      <span v-if="active === d.channel" class="tip bar-tip" role="status">
        <span class="tip-row"><b>{{ money(d.revenue) }}</b><span>{{ pct(d.revenue / total) }} of revenue</span></span>
      </span>
    </li>
  </ul>
</template>
