// app/components/DataTable.vue
<script setup lang="ts" generic="T extends Record<string, any>">
// Sortable, paginated table shared by Orders and Customers.
// Custom cells: <template #cell-total="{ row }">...</template>
import type { Column } from '~/utils/table';

const props = withDefaults(defineProps<{ rows: T[]; columns: Column[]; caption: string; pageSize?: number }>(), { pageSize: 12 });

const sort = ref<{ key: string; dir: 1 | -1 } | null>(null);
const page = ref(0);
watch(() => props.rows, () => { page.value = 0; });

const sorted = computed(() => {
  const s = sort.value;
  if (!s) return props.rows;
  return [...props.rows].sort((a, b) => {
    const x = a[s.key], y = b[s.key];
    return (typeof x === 'number' && typeof y === 'number' ? x - y : String(x).localeCompare(String(y))) * s.dir;
  });
});
const pages = computed(() => Math.max(1, Math.ceil(sorted.value.length / props.pageSize)));
const current = computed(() => Math.min(page.value, pages.value - 1));
const visible = computed(() => sorted.value.slice(current.value * props.pageSize, (current.value + 1) * props.pageSize));

const state = (key: string) => (sort.value?.key === key ? (sort.value.dir === 1 ? 'ascending' : 'descending') : 'none');
const toggle = (key: string) => {
  const s = sort.value;
  sort.value = s?.key === key ? (s.dir === -1 ? { key, dir: 1 } : null) : { key, dir: -1 };
  page.value = 0;
};
const cls = (c: Column) => [c.num && 'num', c.hideSm && 'hide-sm'].filter(Boolean).join(' ') || undefined;
</script>

<template>
  <div v-if="rows.length === 0" class="empty"><slot name="empty" /></div>
  <template v-else>
    <div class="table-wrap">
      <table>
        <caption class="sr-only">{{ caption }}</caption>
        <thead>
          <tr>
            <th v-for="c in columns" :key="c.key" scope="col" :class="cls(c)" :aria-sort="state(c.key)">
              <button type="button" class="th-btn" @click="toggle(c.key)">
                {{ c.label }}
                <Icon :name="state(c.key) === 'ascending' ? 'up' : state(c.key) === 'descending' ? 'down' : 'sort'" :size="14" />
              </button>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="(r, i) in visible" :key="i">
            <td v-for="c in columns" :key="c.key" :class="cls(c)">
              <slot :name="`cell-${c.key}`" :row="r">{{ r[c.key] }}</slot>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="pager">
      <p class="muted">{{ current * pageSize + 1 }}–{{ Math.min(sorted.length, (current + 1) * pageSize) }} of {{ sorted.length }}</p>
      <div class="pager-btns">
        <button type="button" class="icon-btn" :disabled="current === 0" aria-label="Previous page" @click="page = current - 1"><Icon name="left" /></button>
        <span class="muted">Page {{ current + 1 }} of {{ pages }}</span>
        <button type="button" class="icon-btn" :disabled="current >= pages - 1" aria-label="Next page" @click="page = current + 1"><Icon name="right" /></button>
      </div>
    </div>
  </template>
</template>

// src/components/DataTable.tsx
'use client';

import { useMemo, useState } from 'react';
import { Icon } from './Icon';

export type Column<T> = {
  key: keyof T & string;
  label: string;
  num?: boolean;
  hideSm?: boolean; // hidden below 640px so the key columns fit on phones
  render?: (row: T) => React.ReactNode;
};

// Sortable, paginated table shared by Orders and Customers
export default function DataTable<T extends Record<string, unknown>>({ rows, columns, pageSize = 12, caption, empty }: {
  rows: T[];
  columns: Column<T>[];
  pageSize?: number;
  caption: string;
  empty: React.ReactNode;
}) {
  const [sort, setSort] = useState<{ key: string; dir: 1 | -1 } | null>(null);
  const [page, setPage] = useState(0);

  const sorted = useMemo(() => {
    if (!sort) return rows;
    return [...rows].sort((a, b) => {
      const x = a[sort.key], y = b[sort.key];
      return (typeof x === 'number' && typeof y === 'number' ? x - y : String(x).localeCompare(String(y))) * sort.dir;
    });
  }, [rows, sort]);

  const pages = Math.max(1, Math.ceil(sorted.length / pageSize));
  const current = Math.min(page, pages - 1);
  const visible = sorted.slice(current * pageSize, current * pageSize + pageSize);

  const toggle = (key: string) => {
    setSort((s) => (s?.key === key ? (s.dir === -1 ? { key, dir: 1 } : null) : { key, dir: -1 }));
    setPage(0);
  };

  if (rows.length === 0) return <div className="empty">{empty}</div>;

  return (
    <>
      <div className="table-wrap">
        <table>
          <caption className="sr-only">{caption}</caption>
          <thead>
            <tr>
              {columns.map((c) => {
                const state = sort?.key === c.key ? (sort.dir === 1 ? 'ascending' : 'descending') : 'none';
                return (
                  <th key={c.key} scope="col" className={[c.num && 'num', c.hideSm && 'hide-sm'].filter(Boolean).join(' ') || undefined} aria-sort={state}>
                    <button type="button" className="th-btn" onClick={() => toggle(c.key)}>
                      {c.label}
                      <Icon name={state === 'ascending' ? 'up' : state === 'descending' ? 'down' : 'sort'} size={14} />
                    </button>
                  </th>
                );
              })}
            </tr>
          </thead>
          <tbody>
            {visible.map((r, i) => (
              <tr key={i}>
                {columns.map((c) => <td key={c.key} className={[c.num && 'num', c.hideSm && 'hide-sm'].filter(Boolean).join(' ') || undefined}>{c.render ? c.render(r) : String(r[c.key])}</td>)}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <div className="pager">
        <p className="muted">{current * pageSize + 1}–{Math.min(sorted.length, (current + 1) * pageSize)} of {sorted.length}</p>
        <div className="pager-btns">
          <button type="button" className="icon-btn" onClick={() => setPage(current - 1)} disabled={current === 0} aria-label="Previous page"><Icon name="left" /></button>
          <span className="muted">Page {current + 1} of {pages}</span>
          <button type="button" className="icon-btn" onClick={() => setPage(current + 1)} disabled={current >= pages - 1} aria-label="Next page"><Icon name="right" /></button>
        </div>
      </div>
    </>
  );
}
